services:
  discovery-service:
    image: ecommerce-microservices-discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8761
      - SPRING_CLOUD_CONFIG_ENABLED=false
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  config-service:
    image: ecommerce-microservices-config-service
    container_name: config-service
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8888
      - SPRING_CLOUD_CONFIG_ENABLED=false
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  catalogue-service:
    image: ecommerce-microservices-catalogue-service
    container_name: catalogue-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - config-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  commande-service:
    image: ecommerce-microservices-commande-service
    container_name: commande-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
      - config-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8082
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  paiement-service:
    image: ecommerce-microservices-paiement-service
    container_name: paiement-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
      - config-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8083
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  gateway-service:
    image: ecommerce-microservices-gateway-service
    container_name: gateway-service
    ports:
      - "8084:8080"
    depends_on:
      - discovery-service
      - config-service
      - catalogue-service
      - commande-service
      - paiement-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration